name: hc-pkg
on:
  workflow_dispatch: 
    
jobs:
  hcpkgrelease:
    uses: mozilla/hubs-ops/.github/workflows/HcPkgPreReleaseGitops.yaml@master
    with:
      main: master
      releasing: polycosm
      qaTestBranch: qa-test